version: "3"
services:
  postgres_db:
    image: postgres
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres-user123456789
      POSTGRES_USER: postgres-user
      POSTGRES_DB: cityinfo
      PDATA: /var/lib/postgresql/data/pgdata
    container_name: postgres_db
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_LISTEN_PORT=8001
    ports:
      - "8001:8001"
    restart: on-failure
    volumes:
      - pgadmin-volume:/var/lib/pgadmin

volumes:
  postgresql-data:
  pgadmin-volume: